# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'OnsiteTexts' do

pod 'DZNEmptyDataSet'
pod 'APAddressBook'
pod 'NSTimer-Blocks'
pod 'TPKeyboardAvoiding'
pod 'APAddressBook'
pod 'THContactPicker'
pod 'VPPDropDown'

end

target 'OnsiteTextsTests' do

end

